release_name: "web-app"
chart: "../../../charts/nginx_basic"
namespace: "basic"

helm_values:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: p-myapp.local
        paths:
          - path: /
            pathType: Prefix
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70



