# values.yaml
replicaCount: 1

service:
  type: ClusterIP  # Default to ClusterIP for use with ingress
  port: 80
  # nodePort is now optional and only used when type is NodePort
  nodePort: null

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

container:
  image: nginx:latest
  port: 80

probes:
  liveness:
    path: "/"
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: "/"
    initialDelaySeconds: 3
    periodSeconds: 5
