# values.yaml
replicaCount: 3

container:
  image: nginx:alpine
  port: 80
  command: ["/bin/sh"]
  args: ["/config/inject.sh"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "pods.local"
      paths:
        - path: /
          pathType: Prefix


  

